In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error,r2_score

In [3]:
df=pd.read_csv("Hitters.csv")
df=df.dropna()

dms=pd.get_dummies(df[['League', 'Division','NewLeague']])

y=df['Salary']
X_= df.drop(['Salary','League', 'Division','NewLeague'],axis=1).astype('float64')
X= pd.concat([X_, dms[['League_N', 'Division_W','NewLeague_N']]],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

# Model/ Tahmin

In [4]:
from sklearn.svm import SVR

In [19]:
svr_model= SVR(kernel="linear")

In [20]:
svr_model.fit(X_train,y_train)

SVR(kernel='linear')

In [21]:
svr_model.predict(X_train)

array([ 219.32622627,  702.43039317,  623.20559641,  153.77538484,
        463.15191157, 1002.96905384,   55.20051607,  218.47517427,
        466.00937227,  802.1635624 , 1352.57116101,  732.63375149,
        894.1998132 ,  631.61791552,  577.0472608 ,  484.91978275,
       1032.34544981,  116.97512913,  149.91644355,  324.65371133,
        649.27695167,  965.69625709,  446.69482594,  348.72929467,
         55.25455683,  849.64918325,  502.47021073,  240.89994989,
        219.09282257,  301.22750255,   38.53524051,  658.04153098,
        910.8835871 ,  123.94979587,  439.79028139,  234.22077502,
        299.90042901,  650.77556799,  297.91983748,  155.00257753,
        121.32672765,  307.13419364,  183.22159204,  251.32555296,
        194.49102498,  958.89630074,  262.03427945,  519.70478054,
        295.85702596,  429.26122866,  356.23270074,  458.53063755,
        294.78664772,  348.48865569,  650.65632508,  198.82451778,
        490.6241315 ,  632.55863498,  244.37995407, 1434.97416

In [22]:
svr_model.predict(X_test)

array([ 679.14754919,  633.72883529,  925.68639938,  270.28464317,
        530.26659421,  272.22606175,  549.4423224 ,  446.55264396,
        892.8309562 ,  677.96856008,  677.16149322,  868.18485002,
        451.00610659,  382.35543803,  308.26205728,  609.16129527,
        744.69688828,  152.60132455, 1012.03931325,  376.77473896,
        481.42042557,  771.67234151,  521.05069491,  588.93024829,
        615.06797076,  132.39925922,  958.8936008 ,  355.23613415,
        579.89689139,  124.67778281,  153.86174938,   14.75058547,
        358.06037823,  282.58793005,  281.45885316,  533.38953946,
       1206.24281291,  170.07373765,   40.51550058,  258.34330019,
         66.15838195,  216.51484567,  692.01541809,  449.24701051,
        856.67888329,  753.2161061 ,  442.51268754,  288.71673557,
        309.2636209 ,  556.53116993,  867.46283046,  353.4386512 ,
        656.14839681,  362.44007402,  201.08404007,  525.70822384,
        584.05155335,  910.92606662,  178.24959893, 1247.87338

In [23]:
svr_model.intercept_

array([-80.15196063])

In [24]:
svr_model.coef_

array([[ -1.2183904 ,   6.09602978,  -3.67574533,   0.14217072,
          0.51435925,   1.28388992,  12.55922527,  -0.08693754,
          0.46597185,   2.98259931,   0.52944513,  -0.79820793,
         -0.16015531,   0.30872795,   0.28842348,  -1.79560066,
          6.41868986, -10.74313785,   1.33374319]])

In [25]:
# Test 
y_pred=svr_model.predict(X_test)

In [26]:
np.sqrt(mean_squared_error(y_test,y_pred))

370.0408415795005

# Model Tuning

In [28]:
svr_param={"C":[0.1,0.3,0.5,1,3]}

In [29]:
svr_cv_model=GridSearchCV(svr_model,svr_param,cv=5).fit(X_train,y_train)
# verbose=2 işlem yapılırken işlemleri görüntüleyebiliyoruz. Kaç kere fit ediliyor kaç dakika sürüyor gibi gibi
# n_jobs=-1 işlemciyi en yüksek performansta çalıştıracak parametredir. 

In [30]:
svr_cv_model.best_params_

{'C': 0.3}

In [31]:
svr_tuned=SVR(kernel="linear",C=0.3).fit(X_train,y_train)

In [32]:
y_pred=svr_tuned.predict(X_test)

In [34]:
np.sqrt(mean_squared_error(y_test,y_pred))

367.5589588902782