In [35]:
import pandas as pd
df=pd.read_csv("Advertising.csv")
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [90]:
X=df.drop('sales',axis=1)

y=df[["sales"]]

In [91]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [92]:
X.head()


Unnamed: 0     TV  radio  newspaper
0           1  230.1   37.8       69.2
1           2   44.5   39.3       45.1
2           3   17.2   45.9       69.3
3           4  151.5   41.3       58.5
4           5  180.8   10.8       58.4

In [99]:
X=df[["TV","radio","newspaper"]]
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

### Statsmodels ile model kurmak 

In [100]:
import statsmodels.api as sm

In [101]:
lm= sm.OLS(y,X)

In [102]:
model=lm.fit()

In [103]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Fri, 21 Oct 2022   Prob (F-statistic):                   2.43e-171
Time:                        15:44:39   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### R-squared bağımsız değşkenlerin bağımlı değişkeni açıklama yüzdesini verir. 
### F-Statistic modelin anlamlılığını test etmek için kullanılır. 0,05'den küçük olduğu için anlamlıdır diyoruz. 
### coef -> bağımsız değişkenlerin katsayılarını ifade ediyor
### t katsayının anlamlı olup olmadığını anlamamızı sağlar. 

In [104]:
#Scikit learn ile model kurmak 
from sklearn.linear_model import LinearRegression

In [105]:
lm=LinearRegression()

In [106]:
model= lm.fit(X,y)

In [107]:
model.intercept_

array([2.93888937])

In [108]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

## Tahmin 
### Sales = 3 + TV * 0,04 + radio * 0,18 - newspaper * 0,001

In [109]:
new=[[30],[10],[40]]

In [110]:
new=pd.DataFrame(new).T

In [111]:
new

0   1   2
0  30  10  40

In [112]:
model.predict(new)

C:\Users\sevva\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [113]:
from sklearn.metrics import mean_squared_error 

In [114]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [115]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [116]:
MSE=mean_squared_error(y,model.predict(X))

In [117]:
import numpy as np
RMSE= np.sqrt(MSE)
RMSE

1.6685701407225697

# Model Tuning\Model Doğrulama

In [118]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [119]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [120]:
from sklearn.model_selection import train_test_split

In [121]:
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=50)
# Burada random state belirlememizin amacı her çalıştırdığımızda farklı sonuç almamak için

In [122]:
X_train.head()

TV  radio  newspaper
170   50.0   11.6       18.4
183  287.6   43.0       71.8
38    43.1   26.7       35.1
153  171.3   39.7       37.7
40   202.5   22.3       31.6

In [123]:
X_train.shape

(160, 3)

In [124]:
lm=LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [126]:
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

1.7277797764995744

In [127]:
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

1.407032248468741

## K fold Cross Validation

In [128]:
from sklearn.model_selection import cross_val_score

In [129]:
cross_val_score(model,X_train,y_train,cv=10 , scoring="neg_mean_squared_error")

array([-2.45109152, -2.6361596 , -2.0872853 , -3.14286657, -5.22887588,
       -2.20241224, -2.3660001 , -2.30241034, -7.21107964, -2.1250816 ])

In [131]:
#cv mse
np.mean(-cross_val_score(model,X_train,y_train,cv=10 , scoring="neg_mean_squared_error"))

3.175326277558187

In [132]:
np.sqrt(np.mean(-cross_val_score(model,X_train,y_train,cv=10 , scoring="neg_mean_squared_error")))

1.7819445214591243